version: "3.4"

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  backend:
    build:
      context: r_backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      REDIS_HOST: redis
      DB_HOST: db
    depends_on:
      - 'db'
      - 'redis'
      # db:
       # condition: service_completed_successfully
      # redis:
       # condition: service_completed_successfully
  frontend:
    build:
      context: r_frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      API_URL: http://backend:4000/grpahql
    depends_on:
      - 'backend'
     #  backend:
       # condition: service_completed_successfully
